### ISSUE TITLE
Website redesign/improvements)

### ISSUE THREAD

**Issue by raispuro** [raispuro/QuickSketch#6]
Think QuickSketch looks too plain or needs something else to make it look better, or ways to improve it? I'm open to any suggestions!

**Comment by UnlivedMage** [comment]
Would you mind if I work on this issue?
I would like to add substance to the other pages. Add pages and content for About, Login, and Sign Up. I'm not sure how to add functionality to logging in and signing up but I can create a frontend page for it.

**Comment by raispuro** [comment]
> Would you mind if I work on this issue? I would like to add substance to the other pages. Add pages and content for About, Login, and Sign Up. I'm not sure how to add functionality to logging in and signing up but I can create a frontend page for it.

Yes I can assign this to you, for the login and signup I'm not seeking actual back-end functionality at the moment. I'm just looking for the login/signup forms to be there, so that in the future it'll be easier to implement the back-end functionality once those features are added in on a later date.
